// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA04B-3h0d5vPFQ15tf_YLjcp18DfwNyqs',
    appId: '1:577245788003:web:f174ab4054214c2ea94556',
    messagingSenderId: '577245788003',
    projectId: 'projetoflutter-4fe61',
    authDomain: 'projetoflutter-4fe61.firebaseapp.com',
    storageBucket: 'projetoflutter-4fe61.appspot.com',
    measurementId: 'G-R42T7S6W76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoDs1UFLDhgSSNA1M_XrHpOm8ue5r4tL0',
    appId: '1:577245788003:android:28cee3d73361aaaea94556',
    messagingSenderId: '577245788003',
    projectId: 'projetoflutter-4fe61',
    storageBucket: 'projetoflutter-4fe61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZm1IE09Z5yVqLN1ePkSsdFEA696cyBps',
    appId: '1:577245788003:ios:94ade47205ff97a4a94556',
    messagingSenderId: '577245788003',
    projectId: 'projetoflutter-4fe61',
    storageBucket: 'projetoflutter-4fe61.appspot.com',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZm1IE09Z5yVqLN1ePkSsdFEA696cyBps',
    appId: '1:577245788003:ios:94ade47205ff97a4a94556',
    messagingSenderId: '577245788003',
    projectId: 'projetoflutter-4fe61',
    storageBucket: 'projetoflutter-4fe61.appspot.com',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA04B-3h0d5vPFQ15tf_YLjcp18DfwNyqs',
    appId: '1:577245788003:web:2db1115f4b12b41aa94556',
    messagingSenderId: '577245788003',
    projectId: 'projetoflutter-4fe61',
    authDomain: 'projetoflutter-4fe61.firebaseapp.com',
    storageBucket: 'projetoflutter-4fe61.appspot.com',
    measurementId: 'G-S9VGNRJQS1',
  );
}
